In [1]:
import logging
import time
from dataclasses import dataclass,field
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional,Union,Literal
import json
from tqdm import tqdm
from datetime import datetime
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datasets import Dataset
# Pushing data to PostGrad SQL
import psycopg
import uuid
import os
from dotenv import load_dotenv
load_dotenv('.env')

import warnings
warnings.filterwarnings("ignore")

/mnt/d/yota/projects/rag_projects/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline,Pipeline

In [3]:
model_id = 'Qwen/Qwen3-4B-Instruct-2507'
tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype="bfloat16",
)
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    temperature=0.3,
    max_new_tokens=1024,
    max_length=None,
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 398/398 [00:00<00:00, 1224.58it/s]
[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'max_length', 'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

In [5]:
from src.suggestor import FinanceAgentInput,FinanceAgentOutput,FinanceAgent

In [ ]:
finance_input = FinanceAgentInput(
    # company_table_name= 'company_table',
    company_lists_csv = "https://archives.nseindia.com/content/indices/ind_nifty50list.csv",
    stock_table_name= 'stock_news_dataset',
)
agent =FinanceAgent(model=pipe)
finance_out = await agent.execute(finance_input)

2026-07-04 17:30:28,869 - INFO - PSQL Connected Successfully!
2026-07-04 17:30:28,943 - INFO - Company Table loaded with 50 data points.
2026-07-04 17:30:28,943 - INFO - Starting Analysis...
Company :'Adani Enterprises Ltd.' News article :   0%|          | 0/52 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Company :'Adani Enterprises Ltd.' News article :  19%|█▉        | 10/52 [02:18<10:31, 15.02s/it][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Company :'Adani Enterprises Ltd.' News article : 100%|██████████| 52/52 [09:44<00:00, 11.24s/it]
Company :'Adani Ports and Special Economic Zone Ltd.' News article : 100%|██████████| 22/22 [04:20<00:00, 11.83s/it]
Company :'Apollo Hospitals Enterprise Ltd.' News article : 100%|██████████| 23/23 [03:46<00:00,  9.85s/it]
Company :'Asian Paints Ltd.' News article : 100%|██████████| 65/65 [10:56<00:00, 10.09s/it]
Company :'Axis Bank Ltd.' News article : 100%|██████████| 48/48 [09:27<00:00, 11.81s/it]
Company :'Bajaj Auto Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Bajaj Finance Ltd.' News article : 100%|██████████| 48/48 [10:24<00:00, 13.01s/it]
Company :'Bajaj Finserv Ltd.' News article : 100%|██████████| 48/48 [09:39<00:00, 12.08s/it]
Company :'Bharat Electronics Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Bharti Airtel Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Cipla Ltd.' News article : 100%|██████████| 23/23 [03:37<00:00,  9.46s/it]
Company :'Coal India Ltd.' News article : 100%|██████████| 10/10 [01:34<00:00,  9.48s/it]
Company :'Dr. Reddy's Laboratories Ltd.' News article : 100%|██████████| 23/23 [03:25<00:00,  8.95s/it]
Company :'Eicher Motors Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Eternal Ltd.' News article : 100%|██████████| 26/26 [04:38<00:00, 10.72s/it]
Company :'Grasim Industries Ltd.' News article : : 0it [00:00, ?it/s]
Company :'HCL Technologies Ltd.' News article :  13%|█▎        | 21/165 [04:25<31:07, 12.97s/it]

In [ ]:
from src import BaseAgent, AgentInput, AgentOutput
from src import UploadingInput, UploadToPLSQL
from datetime import date

##### System Prompt

In [30]:
# Find relavalnce
SYSTEM_PROMPT = """You are a Senior Financial Market Analyst.

Your task is to analyze ONE financial news article for ONE company.

Evaluate the article only from an investment perspective.

Ignore emotional language.

Determine whether the news is expected to have a positive, negative, or neutral impact on the company or in the sector.

You have to estimate the confidance based on :
    - Clarity of the article
    - Explicit financial impact
    - Presence of concrete facts
    - Ambiguity

Consider:
    - Earnings
    - Revenue
    - Product Launch
    - Partnership
    - Acquisition
    - Regulation
    - Lawsuit
    - Competition
    - Supply Chain
    - Analyst Ratings
    - CEO Changes
    - Market Expansion
    - Share Buybacks
    - Dividends


You have to return only in JSON format without any extra comment like below : 
{{
    "sentiment": Positive / Negagtive / Neutral,
    "sentiment_score": 0.00,
    "confidence": 0.00,
    "event_type": The Type of event described by the Article,
    "impact": Impact of the Article on the Company. High / Medium / Low / No Impact,
    "time_horizon": "Medium",
    "key_positive_factors": [],
    "key_negative_factors": [],
    "reasoning": A described resoning about your analysis.
}}
"""

SUGGESTER_SYSTEM_PROMPT = """You are a Senior Financial Market Analyst and Stock Market Investor.

Your task is to analyze the positive and negative factors of a stock generated by a Junior Financial Analyst and determine whether the stock is a good investment.

You will be provided with the following information:

- List of Positive Factors
- List of Negative Factors
- List of Reasoning created by the Junior Analyst

Instructions:
- Ignore emotional or sensational language.
- Base your decision only on the provided factors and reasoning.
- Consider both short-term and long-term implications before making a recommendation.

Return your response strictly in the following JSON format:

{{
    "Investment": "Yes" | "No" | "Tentative",
    "Time Period": "1-2 Weeks" | "1-2 Months" | "1-2 Years" | "2+ Years",
    "Expected Profit": "<Estimated percentage increase in stock value>"
}}
"""

##### Prompts

In [32]:
PROMPT = """
Company Details : 
    - Name : {company_name}
    - Industry : {industry}

Article : 
    - Title : {title}
    - Content : {content}
"""

SUGGESTER_PROMPT = """Please analyze the news regarding the company "{company}" from "{industry}" industry.

Positive factors : 
{positive_factors}

Negagtive Factors : 
{negagtive_factors}

Reasoning : 
{reasonings}
"""

### Agegnts

In [ ]:
@dataclass
class AnalystAgentInput(AgentInput):
    # company_table_name:str
    company_df:pd.DataFrame
    stock_table_name:str

@dataclass
class AnalystAgentOutput(AgentOutput):
    market_news:Dict

class AnalystAgent(BaseAgent):
    def __init__(self,model:Pipeline):
        super().__init__("Analyst Agent")
        self.model=model
        
        self.conn = psycopg.connect(
                                        host=os.getenv("PS_HOST"),
                                        port=os.getenv("PS_PORT"),
                                        dbname=os.getenv("PS_DBNAME"),
                                        user=os.getenv("PS_USER"),
                                        password=os.getenv("PS_PASSWORD"),
                                    )
        
        self.company_query = """
                        SELECT *
                        FROM {company_table};
                        """
        self.news_query = """
                    SELECT *
                    FROM {stock_table}
                    WHERE SECTOR LIKE '{industry}%'
                    """
        
        self.market_news = dict()
    
    async def execute(self,input_data:AnalystAgentInput) ->AnalystAgentOutput:
        
        self.logger.info(f'Company Table loaded with {input_data.company_df.shape[0]} data points.')

        self.logger.info('Starting Analysis...')

        for idx,row in  input_data.company_df.iterrows():
            company = row['Company Name']
            industry = row['Industry']
            self.market_news[company] = {
                'company' : company,
                'industry': industry,
                'score' : 0.0,
                'sentiments': [],
            }
            news_df = pd.read_sql_query(
                self.news_query.format(
                    stock_table=input_data.stock_table_name,
                    industry=industry
                    ), self.conn
                )

            for idx,row in tqdm(news_df.iterrows(),total=len(news_df), desc=f"Company :'{company}' News article : "):
                message = [
                    {
                        'role':'system',
                        'content' : SYSTEM_PROMPT,
                    },
                    {
                        'role':'user',
                        'content': PROMPT.format(company_name = company,
                                        industry = industry, 
                                        title = row.title, 
                                        content = row.content),
                    },
                ]

                result = self.model(message)
                sentiment = json.loads(result[0]['generated_text'][-1]['content'])
                if sentiment['sentiment'].lower()!='neutral':
                    self.market_news[company]['sentiments'].append(sentiment)
                
            self.market_news[company]['score'] = 0 if len(self.market_news[company]['sentiments'])==0 else sum([sentiment['sentiment_score'] * sentiment['confidence'] for sentiment in self.market_news[company]['sentiments']]) / len(self.market_news[company]['sentiments'])


        return AnalystAgentOutput(
            market_news = self.market_news,
        )

In [43]:
@dataclass
class SuggesterAgentInput(AgentInput):
    market_news:Dict
@dataclass
class SuggesterAgentOutput(AgentOutput):
    suggestions:Dict

class SuggesterAgent(BaseAgent):
    def __init__(self,model:Pipeline):
        super().__init__("Finance Agent")
        self.model=model
        self.company_suggestions = dict()
    
    async def execute(self,input_data:SuggesterAgentInput) ->SuggesterAgentOutput:
        market_news = input_data.market_news
        for company,resoning in market_news.items():
            industry = resoning['industry']
            positive_factors = [ factor for sentiment in resoning['sentiments'] for factor in sentiment['key_positive_factors']]
            negagtive_factors = [ factor for sentiment in resoning['sentiments'] for factor in sentiment['key_negative_factors']]
            reasonings = [
                sentiment["reasoning"]
                for sentiment in resoning["sentiments"]
                if sentiment["sentiment"].lower() != "neutral"
            ]

            positive_factors = '  - ' +"\n  - ".join(positive_factors)
            negagtive_factors = '  - ' +"\n  - ".join(negagtive_factors)
            reasonings = '  - ' +"\n  - ".join(reasonings)
        
            message  = [
                        {
                            'role':'system',
                            'content':SUGGESTER_SYSTEM_PROMPT,
                        },
                        {
                            'role': 'user',
                            'content': SUGGESTER_PROMPT.format(
                                company=company,
                                industry = industry,
                                positive_factors = positive_factors,
                                negagtive_factors = negagtive_factors,
                                reasonings = reasonings,
                            ),
                        }
                    ]
            result = self.model(message)
            output = json.loads(result[0]['generated_text'][-1]['content'])

            self.company_suggestions[company] = output

        return SuggesterAgentOutput(
            suggestions = self.company_suggestions
            )

In [ ]:
@dataclass
class FinanceAgentInput(AgentInput):
    # company_table_name:str
    company_lists_csv:str
    stock_table_name:str
@dataclass
class FinanceAgentOutput(AgentOutput):
    stocks:Dict

class FinanceAgent(BaseAgent):
    def __init__(self,model:Pipeline):
        super().__init__("Finance Agent")
        self.model=model
        self.analyst_agent = AnalystAgent(self.model)
        self.suggestion_agent = SuggesterAgent(self.model)
        self.psql_uploader = UploadToPLSQL()
    
    async def execute(self,input_data:FinanceAgentInput) ->FinanceAgentOutput:
        company_df = pd.read_csv(input_data.company_lists_csv)
        analyst_input = AnalystAgentInput(
            # company_table_name=input_data.company_table_name,
            company_df = company_df,
            stock_table_name=input_data.stock_table_name,
        )
        analyst_out = await self.analyst_agent.execute(analyst_input)

        suggestion_input = SuggesterAgentInput(
            market_news=analyst_out.market_news
        )

        suggegstion_output = await self.suggestion_agent.execute(suggestion_input)

        investment_sugggestions = pd.DataFrame(
            [[key,value['Investment'],value['Time Period'],value['Expected Profit']] for key,value in suggegstion_output.suggestions.items()],
            columns = ['Industry','Investment','Time Period','Expected Profit']
        )
        investment_sugggestions['Date'] = date.today()

        self.logger.info('Uploading to PSQL...')

        psql_input = UploadingInput(
                                dataset = investment_sugggestions,
                                uploading_columns = ['Industry','Investment',	'Time Period',	'Expected Profit',	'Date'],
                                sql_column_names = ['id', 'company','investment','time_period','expected_profit','created_at'],
                                table_name= 'stock_suggestions',
                            )
        
        self.psql_uploader._truncate_table(psql_input.table_name)
        await self.psql_uploader.execute(psql_input)

        return FinanceAgentOutput(
            stocks = investment_sugggestions,
        )

In [ ]:
finance_input = FinanceAgentInput(
    # company_table_name= 'company_table',
    company_lists_csv = "https://archives.nseindia.com/content/indices/ind_nifty50list.csv",
    stock_table_name= 'stock_news_dataset',
)
agent =FinanceAgent(model=pipe)
finance_out = await agent.execute(finance_input)

2026-07-04 15:40:50,377 - INFO - Company Table loaded with 5 data points.
2026-07-04 15:40:50,377 - INFO - Company Table loaded with 5 data points.
2026-07-04 15:40:50,378 - INFO - Starting Analysis...
2026-07-04 15:40:50,378 - INFO - Starting Analysis...
Company :'Larsen & Toubro Ltd.' News article : : 0it [00:00, ?it/s]
Company :'ICICI Prudential Life Insurance Company Ltd.' News article : 100%|██████████| 48/48 [07:27<00:00,  9.33s/it]
Company :'ITI Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Hyundai Motor India Ltd.' News article : : 0it [00:00, ?it/s]
Company :'HDB Financial Services Ltd.' News article : 100%|██████████| 48/48 [07:44<00:00,  9.67s/it]

In [49]:
suggestions = finance_out.stocks.suggestions

In [59]:
investment_sugggestions = pd.DataFrame(
    [[key,value['Investment'],value['Time Period'],value['Expected Profit']] for key,value in suggestions.items()],
    columns = ['Industry','Investment','Time Period','Expected Profit']
)
investment_sugggestions['Date'] = date.today()

In [60]:
investment_sugggestions

,Industry,Investment,Time Period,Expected Profit,Date
0,Larsen & Toubro Ltd.,Tentative,1-2 Years,8%,2026-07-04
1,ICICI Prudential Life Insurance Company Ltd.,Tentative,1-2 Years,12%,2026-07-04
2,ITI Ltd.,No,1-2 Years,0%,2026-07-04
3,Hyundai Motor India Ltd.,Tentative,1-2 Years,10%,2026-07-04
4,HDB Financial Services Ltd.,Tentative,1-2 Years,15%,2026-07-04

In [63]:
psql_input = UploadingInput(
    dataset = investment_sugggestions,
    uploading_columns = ['Industry','Investment',	'Time Period',	'Expected Profit',	'Date'],
    sql_column_names = ['id', 'company','investment','time_period','expected_profit','created_at'],
    table_name= 'stock_suggestions',
)

uploader = UploadToPLSQL()
# uploader._truncate_table(psql_input.table_name)
await uploader.execute(psql_input)

2026-07-04 16:39:58,582 - INFO - PSQL Connected Successfully!

2026-07-04 16:39:58,582 - INFO - PSQL Connected Successfully!
2026-07-04 16:39:58,590 - INFO - All records are uploaded to SQL!
2026-07-04 16:39:58,590 - INFO - All records are uploaded to SQL!

In [64]:
link_for_listed_company = "https://archives.nseindia.com/content/indices/ind_nifty50list.csv"
company_df = pd.read_csv(link_for_listed_company)

In [65]:
company_df

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP,EQ,INE437A01024
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT,EQ,INE021A01026
4,Axis Bank Ltd.,Financial Services,AXISBANK,EQ,INE238A01034
5,Bajaj Auto Ltd.,Automobile and Auto Components,BAJAJ-AUTO,EQ,INE917I01010
6,Bajaj Finance Ltd.,Financial Services,BAJFINANCE,EQ,INE296A01032
7,Bajaj Finserv Ltd.,Financial Services,BAJAJFINSV,EQ,INE918I01026
8,Bharat Electronics Ltd.,Capital Goods,BEL,EQ,INE263A01024
9,Bharti Airtel Ltd.,Telecommunication,BHARTIARTL,EQ,INE397D01024
10,Cipla Ltd.,Healthcare,CIPLA,EQ,INE059A01026
11,Coal India Ltd.,Oil Gas & Consumable Fuels,COALINDIA,EQ,INE522F01014
12,Dr. Reddy's Laboratories Ltd.,Healthcare,DRREDDY,EQ,INE089A01031
13,Eicher Motors Ltd.,Automobile and Auto Components,EICHERMOT,EQ,INE066A01021
14,Eternal Ltd.,Consumer Services,ETERNAL,EQ,INE758T01015
15,Grasim Industries Ltd.,Construction Materials,GRASIM,EQ,INE047A01021
16,HCL Technologies Ltd.,Information Technology,HCLTECH,EQ,INE860A01027
17,HDFC Bank Ltd.,Financial Services,HDFCBANK,EQ,INE040A01034
18,HDFC Life Insurance Company Ltd.,Financial Services,HDFCLIFE,EQ,INE795G01014
19,Hindalco Industries Ltd.,Metals & Mining,HINDALCO,EQ,INE038A01020
20,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,HINDUNILVR,EQ,INE030A01027
21,ICICI Bank Ltd.,Financial Services,ICICIBANK,EQ,INE090A01021
22,ITC Ltd.,Fast Moving Consumer Goods,ITC,EQ,INE154A01025
23,Infosys Ltd.,Information Technology,INFY,EQ,INE009A01021
24,InterGlobe Aviation Ltd.,Services,INDIGO,EQ,INE646L01027
25,JSW Steel Ltd.,Metals & Mining,JSWSTEEL,EQ,INE019A01038
26,Jio Financial Services Ltd.,Financial Services,JIOFIN,EQ,INE758E01017
27,Kotak Mahindra Bank Ltd.,Financial Services,KOTAKBANK,EQ,INE237A01036
28,Larsen & Toubro Ltd.,Construction,LT,EQ,INE018A01030
29,Mahindra & Mahindra Ltd.,Automobile and Auto Components,M&M,EQ,INE101A01026
30,Maruti Suzuki India Ltd.,Automobile and Auto Components,MARUTI,EQ,INE585B01010
31,Max Healthcare Institute Ltd.,Healthcare,MAXHEALTH,EQ,INE027H01010
32,NTPC Ltd.,Power,NTPC,EQ,INE733E01010
33,Nestle India Ltd.,Fast Moving Consumer Goods,NESTLEIND,EQ,INE239A01024
34,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,ONGC,EQ,INE213A01029
35,Power Grid Corporation of India Ltd.,Power,POWERGRID,EQ,INE752E01010
36,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,RELIANCE,EQ,INE002A01018
37,SBI Life Insurance Company Ltd.,Financial Services,SBILIFE,EQ,INE123W01016
38,Shriram Finance Ltd.,Financial Services,SHRIRAMFIN,EQ,INE721A01047
39,State Bank of India,Financial Services,SBIN,EQ,INE062A01020
40,Sun Pharmaceutical Industries Ltd.,Healthcare,SUNPHARMA,EQ,INE044A01036
41,Tata Consultancy Services Ltd.,Information Technology,TCS,EQ,INE467B01029
42,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,TATACONSUM,EQ,INE192A01025
43,Tata Motors Passenger Vehicles Ltd.,Automobile and Auto Components,TMPV,EQ,INE155A01022
44,Tata Steel Ltd.,Metals & Mining,TATASTEEL,EQ,INE081A01020
45,Tech Mahindra Ltd.,Information Technology,TECHM,EQ,INE669C01036
46,Titan Company Ltd.,Consumer Durables,TITAN,EQ,INE280A01028
47,Trent Ltd.,Consumer Services,TRENT,EQ,INE849A01020
48,UltraTech Cement Ltd.,Construction Materials,ULTRACEMCO,EQ,INE481G01011
49,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022

In [5]:
conn = psycopg.connect(
    host=os.getenv("PS_HOST"),
    port=os.getenv("PS_PORT"),
    dbname=os.getenv("PS_DBNAME"),
    user=os.getenv("PS_USER"),
    password=os.getenv("PS_PASSWORD"),
)

In [6]:
company_table = 'company_table'
stock_table = "stock_news_dataset"
company_query = f"""
SELECT *
FROM {company_table};
"""
news_query = """
SELECT *
FROM {stock_table}
WHERE SECTOR LIKE '{industry}%'
"""
company_df= pd.read_sql_query(company_query,conn)
company_df =  company_df.sample(5)

In [7]:
market_news = dict()
for idx,row in  company_df.iterrows():
    company = row.company_name
    industry = row.industry
    market_news[company] = {
        'company' : company,
        'industry': industry,
        'score' : 0.0,
        'sentiments': [],
    }
    news_df = pd.read_sql_query(news_query.format(stock_table=stock_table,industry=industry), conn)

    for idx,row in tqdm(news_df.iterrows(),total=len(news_df), desc=f"Company :'{company}' News article : "):
        message = [
            {
                'role':'system',
                'content' : SYSTEM_PROMPT,
            },
            {
                'role':'user',
                'content': PROMPT.format(company_name = company,
                                industry = industry, 
                                title = row.title, 
                                content = row.content),
            },
        ]

        result = pipe(message)
        sentiment = json.loads(result[0]['generated_text'][-1]['content'])
        if sentiment['sentiment'].lower()!='neutral':
            market_news[company]['sentiments'].append(sentiment)
        
    market_news[company]['score'] = 0 if len(market_news[company]['sentiments'])==0 else sum([sentiment['sentiment_score'] * sentiment['confidence'] for sentiment in market_news[company]['sentiments']]) / len(market_news[company]['sentiments'])

Company :'Sundaram Finance Ltd.' News article :   0%|          | 0/48 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Company :'Sundaram Finance Ltd.' News article :  21%|██        | 10/48 [01:36<05:34,  8.81s/it][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Company :'Sundaram Finance Ltd.' News article : 100%|██████████| 48/48 [07:30<00:00,  9.38s/it]
Company :'Signatureglobal (India) Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Central Depository Services (India) Ltd.' News article : 100%|██████████| 48/48 [07:41<00:00,  9.62s/it]
Company :'Premier Energies Ltd.' News article : : 0it [00:00, ?it/s]
Company :'Anupam Rasayan India Ltd.' News article : : 0it [00:00, ?it/s]

In [8]:
market_news

{'Sundaram Finance Ltd.': {'company': 'Sundaram Finance Ltd.',
  'industry': 'Financial Services',
  'score': 0.56825,
  'sentiments': [{'sentiment': 'Negative',
    'sentiment_score': 0.35,
    'confidence': 0.92,
    'event_type': 'Earnings and Revenue Performance',
    'impact': 'Medium',
    'time_horizon': 'Medium',
    'key_positive_factors': ['Strong medium-term prospects in metro and defence segments',
     'Steady revenue growth guidance of 15-25% over next three years',
     'Improving operating leverage supporting margins',
     'Rail and metro segment expected to contribute Rs 20 billion in FY27 (100% YoY growth)',
     'FY27 order inflow guidance of Rs 150 billion with closing order book of Rs 240 billion'],
    'key_negative_factors': ['Q4 FY26 net profit declined 37.4% YoY to Rs 180 crore',
     'Full-year FY26 net profit down 51.7% to Rs 141 crore',
     'EBITDA declined 35.9% YoY to Rs 271 crore',
     'EBITDA margin contracted to 15.1% from 25.6%',
     'FY26 closing order book at Rs 159 billion, below Rs 200 billion target due to delayed mining tenders',
     'FY27 earnings estimates cut by 2%, 4%, and 10% for FY27, FY28, and FY29 respectively due to supply chain constraints'],
    'reasoning': "The article reports a significant deterioration in Sundaram Finance Ltd.'s financial performance, though the company is not directly mentioned in the article. The content primarily discusses BEML, a defence and infrastructure company, which is unrelated to Sundaram Finance Ltd. Therefore, the article has no direct financial or operational relevance to Sundaram Finance Ltd. The confusion arises from the title and content referencing BEML, not Sundaram Finance. As such, the news event described does not impact Sundaram Finance Ltd. in any material way. The sentiment and impact are therefore neutral with respect to the company in question. However, due to the misattribution in the prompt (the article is about BEML, not Sundaram Finance), and the absence of any mention of Sundaram Finance, the correct assessment is that the article has no impact on the company. This leads to a neutral sentiment and no impact. The initial analysis was based on a misreading of the company name. Correcting this, the article does not pertain to Sundaram Finance Ltd. at all."},
   {'sentiment': 'Positive',
    'sentiment_score': 0.85,
    'confidence': 0.95,
    'event_type': 'Founder Biography and Company Growth History',
    'impact': 'High',
    'time_horizon': 'Medium',
    'key_positive_factors': ['Kotak Mahindra Bank is now a leading private bank in India with a market capitalisation of over Rs 4 lakh crore',
     'Strong historical foundation with clear milestones: start with Rs 30 lakh, 3 employees, expansion through partnerships with Goldman Sachs, entry into mutual funds and investment banking',
     'Successful conversion from non-banking finance company to a bank in 2003, first of its kind in India',
     'Strategic acquisition of Goldman Sachs stake for USD 75 million in 2006, enhancing credibility and global reach',
     "Uday Kotak's vision and leadership contributed to significant value creation and stakeholder benefits",
     'Over 1 lakh direct jobs created, indicating strong employment impact'],
    'key_negative_factors': [],
    'reasoning': "The article provides a detailed historical narrative of Uday Kotak's journey and the growth of Kotak Mahindra Bank. While it does not report on current earnings, revenue, or recent financial performance, it highlights concrete, factual milestones such as the company's founding with a small capital, strategic partnerships (Goldman Sachs), regulatory milestones (RBI license, conversion to bank), and significant market capitalisation (Rs 4 lakh crore). These are strong indicators of long-term success and institutional strength. The article also emphasizes the company's value creation, job generation, and leadership vision, which are positive signals for investors. There is no mention of any negative events such as regulatory issues, lawsuits, declining revenue, or leadership problems. The sentiment is clearly positive due to the emphasis on growth, resilience, and market success. The confidence is high due to the clarity of facts, explicit financial outcomes (market cap, investment returns), and absence of ambiguity. The impact is high as it reinforces the company's credibility and long-term growth trajectory, especially in the financial services sector. The time horizon is medium because the historical narrative supports future stability and growth, though no immediate financial data is provided."},
   {'sentiment': 'Positive',
    'sentiment_score': 0.85,
    'confidence': 0.95,
    'event_type': 'Analyst Rating and Growth Outlook',
    'impact': 'High',
    'time_horizon': 'Medium',
    'key_positive_factors': ["DAM Capital reiterates 'BUY' rating with target price of Rs 13,500 (12% upside)",
     'Expected volume growth of 43.5mn in FY27 and 58mn in FY28 (2% upgrade)',
     'Positive impact from Vivo JV (10mn vols in H2FY27E)',
     'Policy tailwinds including PLI 2.0 and growing preference for Indian EMS vendors',
     'Export push and potential shift in volumes from competitors',
     'New growth avenues in IT/telecom, EMS, and optical transceivers',
     'Strong earnings outlook: 50% EPS CAGR (FY26–28E), 30% RoCE, healthy FCF',
     'Re-rating potential due to increased certainty in key drivers'],
    'key_negative_factors': ['Near-term margin pressure (3.2% margin, 60bps YoY decline due to delayed component initiatives)',
     'Scale-up and approvals remain key uncertainties'],
    'reasoning': 'The article details a positive analyst outlook from DAM Capital on Dixon Technologies, focusing on volume growth drivers such as the Vivo JV, policy support (PLI 2.0), and export expansion. While it acknowledges near-term margin pressures due to delayed component initiatives, the overall narrative is strongly bullish on future earnings and volume growth. The article provides concrete financial metrics (volume targets, EPS CAGR, RoCE, FCF), clear event triggers (Vivo JV, PLI 2.0), and explicit financial impact (target price, upside). The clarity, specificity, and presence of measurable financial outcomes significantly increase confidence. Although margins are under pressure in the near term, the long-term growth trajectory and diversification into new segments are seen as sustainable. The event is not directly related to Sundaram Finance Ltd., so there is no material impact on the company in question. However, since the query specifies Sundaram Finance Ltd. and the article is about Dixon Technologies, the article has no direct relevance to Sundaram Finance. Therefore, the sentiment and impact analysis must be corrected to reflect that the article is about a different company. Thus, the correct sentiment and impact for Sundaram Finance Ltd. should be Neutral, as the article does not mention or affect Sundaram Finance at all.'},
   {'sentiment': 'Positive',
    'sentiment_score': 0.85,
    'confidence': 0.95,
    'event_type': 'Earnings and Share Buyback',
    'impact': 'High',
    'time_horizon': 'Medium',
    'key_positive_factors': ['12% year-on-year revenue growth to Rs 1373 crores in Q4 FY26',
     'EBITDA margin improved to 19.19% (up from 11.33%) with 90% YoY growth in EBITDA',
     'Goldman Sachs maintains buy rating with revised target price of ₹1,330 (9% upside)',
     'Raised FY27 and FY28 earnings estimates by 4-5% due to product mix and gas price assumptions',
     'Share buyback of up to ₹297 crore (1.35% of equity) at ₹1,380 per share',
     'Final dividend of ₹6 per share recommended for FY26'],
    'key_negative_factors': [],
    'reasoning': 'The article provides clear, concrete financial data including strong Q4 FY26 revenue and EBITDA growth, margin expansion, and a positive analyst rating with upside target. The product mix shift to higher-margin glazed vitrified tiles and expected gas price moderation in FY28 support long-term profitability. The share buyback and dividend recommendation enhance shareholder value. All key financial metrics are explicitly stated with forward-looking assumptions. There is no negative event such as a lawsuit, regulatory issue, or supply chain disruption. The sentiment is clearly positive due to strong earnings, margin improvement, and institutional support. The confidence is high due to clarity, explicit financials, and absence of ambiguity.'},
   {'sentiment': 'Negative',
    'sentiment_score': 0.35,
    'confidence': 0.95,
    'event_type': 'Global Market Sentiment and Sector Volatility',
    'impact': 'Low',
    'time_horizon': 'Medium',
    'key_positive_factors': [],
    'key_negative_factors': ['Negative global sentiment in semiconductor and AI sectors affecting investor confidence',
     'Spillover risk to Indian equities due to risk-off flows from global markets',
     'Pressure on technology stocks in India as global demand for semiconductors is questioned'],
    'reasoning': "The article discusses a sharp decline in South Korea's KOSPI driven by semiconductor and AI sector sell-offs, primarily due to falling prices of chipmakers like Samsung and SK Hynix. While Sundaram Finance Ltd. operates in financial services and is not directly exposed to semiconductor stocks, the broader market volatility and reduced global risk appetite could indirectly affect investor sentiment in emerging markets like India. This may lead to temporary reductions in foreign institutional investor (FII) exposure to Indian equities, potentially impacting financial services stocks through reduced capital flows or risk-off behavior. However, there is no direct mention of Sundaram Finance's earnings, revenue, product launches, regulatory changes, or any specific financial event tied to the company. The impact is therefore indirect and limited to macro-level market sentiment. The clarity of the article is high, with concrete facts about market movements and sectoral pressures. The financial impact on Sundaram Finance is not explicit, making the overall impact on the company low. Confidence is high due to clear facts and absence of ambiguity."},
   {'sentiment': 'Negative',
    'sentiment_score': 0.35,
    'confidence': 0.95,
    'event_type': 'Platform Shutdown and Regulatory Impact',
    'impact': 'Low',
    'time_horizon': 'Medium',
    'key_positive_factors': [],
    'key_negative_factors': ['Closure of Dream Money platform, which offered financial products like mutual funds, digital gold, FDs, and loans',
     'No new investments or loan applications will be accepted',
     'Active SIPs will be cancelled from July 7, 2026',
     'Regulatory headwinds from government ban on RMG and retrospective 28% GST on bets',
     'Industry-wide shift indicating weakening of fintech diversification in RMG companies'],
    'reasoning': "The article describes the shutdown of Dream Money, a fintech platform launched by Dream Sports (parent of Dream11), which operated financial products including mutual funds, digital gold, fixed deposits, and loans. While the company assures that customer investments remain safe and will be migrated to partners, the closure represents a significant reduction in its financial services footprint. The shutdown is directly linked to regulatory pressure from the government's 2025 ban on real-money gaming (RMG) and the retrospective 28% GST on RMG bets. This regulatory environment is negatively impacting the broader RMG sector, leading to strategic retreats. However, the impact on Sundaram Finance Ltd. is indirect and not directly tied to the event. Sundaram Finance is a separate financial services company and not affiliated with Dream Sports or Dream Money. Therefore, the event has no direct financial, operational, or revenue impact on Sundaram Finance Ltd. The sentiment is negative due to the broader regulatory headwinds and sectoral decline, but the impact on Sundaram Finance is negligible. The clarity of the article is high, with concrete facts about the shutdown timeline, product migration, and regulatory context. The absence of any direct mention of Sundaram Finance or its financials confirms no direct impact. Thus, the confidence is high due to clear facts and absence of ambiguity, though the event is sector-adjacent, not company-specific."}]},
 'Signatureglobal (India) Ltd.': {'company': 'Signatureglobal (India) Ltd.',
  'industry': 'Realty',
  'score': 0,
  'sentiments': []},
 'Central Depository Services (India) Ltd.': {'company': 'Central Depository Services (India) Ltd.',
  'industry': 'Financial Services',
  'score': 0.613375,
  'sentiments': [{'sentiment': 'Negative',
    'sentiment_score': 0.35,
    'confidence': 0.92,
    'event_type': 'Earnings and Revenue Performance',
    'impact': 'Medium',
    'time_horizon': 'Medium',
    'key_positive_factors': ['Strong medium-term prospects in metro and defence segments',
     'Steady revenue growth guidance of 15-25% over next three years',
     'Improving operating leverage supporting margins',
     'Rail and metro segment expected to contribute Rs 20 billion in FY27 (100% YoY growth)',
     'FY27 order inflow guidance of Rs 150 billion with closing order book of Rs 240 billion'],
    'key_negative_factors': ['Q4 FY26 net profit down 37.4% YoY to Rs 180 crore',
     'Full-year FY26 net profit down 51.7% to Rs 141 crore',
     'EBITDA down 35.9% YoY to Rs 271 crore',
     'EBITDA margin contracted to 15.1% from 25.6%',
     'FY26 closing order book at Rs 159 billion, below Rs 200 billion target due to deferral of mining tenders',
     'Earnings estimates cut by 2%, 4%, and 10% for FY27, FY28, and FY29 respectively due to supply chain constraints'],
    'reasoning': "The article reports a significant deterioration in Central Depository Services (India) Ltd.'s (CDSL) financial performance, though the company is not the subject of the article. The article discusses BEML, a different company in the defence and infrastructure sector, and contains no direct information about CDSL. Therefore, the news has no material impact on Central Depository Services (India) Ltd. The content is misaligned with the company in question. The article's focus on BEML's earnings decline, order book shortfall, and supply chain issues does not reflect any event affecting CDSL. As a result, despite the detailed financial data, the event has no relevance to CDSL. The sentiment and impact are therefore neutral with respect to the company in question. However, due to the misattribution in the prompt, the article is incorrectly applied to CDSL. Correcting this, the news has no impact on CDSL. Thus, the proper sentiment is Neutral, and the impact is No Impact."},
   {'sentiment': 'Positive',
    'sentiment_score': 0.75,
    'confidence': 0.92,
    'event_type': 'Regulation and Fiscal Policy',
    'impact': 'Medium',
    'time_horizon': 'Medium',
    'key_positive_factors': ['Increased focus on technology-driven growth (AI, machine learning, data centres, IT services)',
     'Boost to MSMEs with ₹10,000 crore dedicated funding',
     'Emphasis on capital goods manufacturing and import reduction',
     'Fiscal prudence and reform measures improving investor confidence',
     'Strong push on infrastructure and logistics supporting long-term growth'],
    'key_negative_factors': [],
    'reasoning': "The article discusses the Union Budget 2026 and its broader economic and policy implications, including a temporary market reaction to an increased Securities Transaction Tax (STT), which the minister characterizes as a necessary step to curb speculation. While the STT increase caused short-term market volatility, the government's emphasis on technology, manufacturing, MSMEs, and infrastructure is seen as a positive long-term tailwind for the financial services sector. Central Depository Services (India) Ltd., as a key player in securities settlement and depository services, benefits from a more stable and growth-oriented financial ecosystem. The policy focus on digital infrastructure, AI, and modern financial services aligns with the company's core operations. Although no direct financial metric (revenue, earnings, or product launch) is mentioned, the overall fiscal and regulatory environment is expected to improve investor sentiment and demand for securities settlement services. The clarity of the article, presence of concrete policy details (e.g., ₹10,000 crore for MSMEs, focus on capital goods), and explicit positive framing of reforms support a medium-term positive impact. The impact is medium due to indirect benefits and the absence of direct operational or financial events tied to the company. Confidence is high due to clear, factual policy statements and alignment with sectoral growth drivers."},
   {'sentiment': 'Positive',
    'sentiment_score': 0.85,
    'confidence': 0.95,
    'event_type': 'Leadership Change and Company Growth',
    'impact': 'High',
    'time_horizon': 'Medium',
    'key_positive_factors': ['Kotak Mahindra Bank has a market capitalisation of over Rs 4 lakh crore, indicating strong financial performance and market valuation.',
     'The company has grown from a small startup with Rs 30 lakh and 3 employees to a leading private bank in India, demonstrating successful scaling and business model viability.',
     'Strategic partnerships with Goldman Sachs (first joint venture in India) and expansion into investment banking, mutual funds, and brokering have enhanced service offerings and revenue streams.',
     "Uday Kotak's vision and leadership have contributed to creating value for stakeholders and over 1 lakh direct jobs.",
     "The company's long-term growth trajectory is reinforced by its strong brand, institutional foundation, and market position."],
    'key_negative_factors': [],
    'reasoning': "The article provides a detailed narrative of the founding and growth of Kotak Mahindra Bank, highlighting key milestones such as the initial capital investment, strategic partnerships, regulatory milestones (conversion to bank in 2003), and expansion into diversified financial services. While it mentions Uday Kotak's resignation as CEO in 2023, the context emphasizes his legacy, vision, and the enduring strength of the institution. There is no mention of any negative financial events, regulatory issues, declining revenue, or operational challenges. The financial impact is clearly positive, with explicit data on market capitalisation (Rs 4 lakh crore), job creation, and historical growth. The article is factually clear, contains concrete financial and operational facts, and presents a consistent narrative of success. The resignation of the CEO is framed as a natural transition and a continuation of the company's long-term vision, not a sign of instability. Therefore, the overall sentiment is positive with high confidence due to the clarity, explicit financial impact, and absence of ambiguity or negative indicators."},
   {'sentiment': 'Positive',
    'sentiment_score': 0.85,
    'confidence': 0.95,
    'event_type': 'Analyst Rating and Growth Outlook',
    'impact': 'High',
    'time_horizon': 'Medium',
    'key_positive_factors': ["DAM Capital reiterates 'BUY' rating with target price of Rs 13,500 (12% upside)",
     'Expected volume growth of 43.5mn in FY27 and 58mn in FY28 (2% upgrade)',
     'Positive impact from Vivo JV (10mn vols in H2FY27E)',
     'Policy tailwinds including PLI 2.0 and growing preference for Indian EMS vendors',
     'Export push and potential shift in volumes from competitors',
     'New growth avenues in IT/telecom, EMS, and optical transceivers',
     'Strong earnings outlook: 50% EPS CAGR (FY26–28E), 30% RoCE, healthy FCF',
     'Potential for re-rating due to increased certainty in key drivers'],
    'key_negative_factors': ['Near-term margin pressures (3.2% margin, 60bps YoY decline due to delayed component initiatives)',

In [9]:
#### Resoning

In [15]:
company = 'Sundaram Finance Ltd.'
resoning = market_news[company]
industry = resoning['industry']

positive_factors = [ factor for sentiment in resoning['sentiments'] for factor in sentiment['key_positive_factors']]
negagtive_factors = [ factor for sentiment in resoning['sentiments'] for factor in sentiment['key_negative_factors']]
reasonings = [
    sentiment["reasoning"]
    for sentiment in resoning["sentiments"]
    if sentiment["sentiment"].lower() != "neutral"
]


positive_factors = '  - ' +"\n  - ".join(positive_factors)
negagtive_factors = '  - ' +"\n  - ".join(negagtive_factors)
reasonings = '  - ' +"\n  - ".join(reasonings)

prompt = f"""Please analyze the news regarding the company "{company}" from "{industry}" industry.

Positive factors : 
{positive_factors}

Negagtive Factors : 
{negagtive_factors}

Reasoning : 
{reasonings}
"""

In [16]:
message  = [
    {
        'role':'system',
        'content':RESONING_SYSTEM_PROMPT,
    },
    {
        'role': 'user',
        'content': prompt,
    }
]

In [25]:
result = pipe(message)
output = json.loads(result[0]['generated_text'][-1]['content'])

In [26]:
output

{'Investment': 'Tentative',
 'Time Period': '1-2 Years',
 'Expected Profit': '12%'}

In [8]:
for idx,row in tqdm(news_df.iterrows(),total=len(news_df)):
    message = [
        {
            'role':'system',
            'content' : SYSTEM_PROMPT,
        },
        {
            'role':'user',
            'content': PROMPT.format(company_name = company,
                            industry = industry, 
                            title = row.title, 
                            content = row.content),
        },
    ]

    result = pipe(message)
    sentiment = json.loads(result[0]['generated_text'][-1]['content'])
    # if sentiment['sentiment'].lower()!='neutral':
    market_news[company]['sentiments'].append(sentiment)
    
market_news[company]['score'] = 0 if len(market_news[company]['sentiments'])==0 else sum([sentiment['sentiment_score'] * sentiment['confidence'] for sentiment in market_news[company]['sentiments']]) / len(market_news[company]['sentiments'])

  0%|          | 0/17 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
 59%|█████▉    | 10/17 [01:17<00:53,  7.70s/it][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 17/17 [02:10<00:00,  7.68s/it]

In [12]:
market_news[company]

{'company': 'eClerx Services Ltd.',
 'industry': 'Services',
 'score': 0.0,
 'sentiments': [{'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.3,
   'event_type': 'Regulation',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses the exhaustion of the US EB-5 visa quota for Indian nationals and related regulatory changes, which is a matter of immigration policy affecting potential investors. However, eClerx Services Ltd. is a services company with no direct involvement in the EB-5 visa process, investor immigration, or related financial flows. There is no mention of eClerx's earnings, revenue, operations, or any financial or operational link to the EB-5 program. Therefore, the news has no direct or indirect financial impact on the company. The event is sector- or market-level, not company-specific. The confidence is low due to the lack of concrete connection between the event and eClerx's business model or performance."},
  {'company': 'Lenskart',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.92,
   'event_type': 'Block Deal (Share Sale by Investor)',
   'impact': 'Low',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article describes a secondary block deal where an ADIA-backed investor (Platinum Jasmine A 2018 Trust) sells approximately 2.3% of Lenskart's equity at Rs 490 per share, resulting in a deal size of Rs 1,960 crore. The transaction is purely a shareholder exit, with no proceeds to the company, and does not affect earnings, revenue, or operations. The investor's stake declines from 12.08% to 9.8%, but ADIA remains a significant shareholder. The deal is part of a broader trend of early investor dilution, not impacting financial performance or strategic direction. No new product launches, partnerships, regulatory changes, or competitive shifts are mentioned. The event is secondary in nature and does not alter the company's financial health or growth trajectory. Therefore, the impact is neutral with low operational or financial consequences. The clarity of facts (price, percentage, deal size, lock-up) is high, and the financial impact is explicitly defined and concrete, supporting high confidence in the neutral assessment."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.95,
   'event_type': 'Regulation / Government Policy',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses Vedanta Group's large-scale industrial projects in Odisha and government oversight of their execution, including fortnightly reviews. However, eClerx Services Ltd. is not mentioned or referenced in the article. The content is entirely focused on Vedanta's investments and infrastructure plans, which are unrelated to eClerx's business operations. As such, there is no direct or indirect financial impact on eClerx Services Ltd. from this news. The event is relevant to the broader industrial sector in Odisha but does not affect eClerx's revenue, earnings, product pipeline, or market position. Therefore, the impact on eClerx is neutral with no material financial implications."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.8,
   'event_type': 'Regulation',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses the proposed 8th Pay Commission salary revisions for central government employees, including a potential increase in apex-level salaries to Rs 10.95 lakh per month. However, eClerx Services Ltd. is a private-sector services company and is not directly affected by government salary reforms or pay commission recommendations. There is no mention of any financial impact, partnership, revenue change, market expansion, or operational link between eClerx and the central government pay structure. The event is purely a regulatory discussion within the public sector and does not influence eClerx's earnings, costs, or business model. Therefore, the impact on the company is negligible and can be classified as no impact. The clarity of the article is high, and the financial relevance to eClerx is absent, resulting in a neutral sentiment with high confidence in the absence of any direct connection."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.0,
   'event_type': 'Cryptocurrency Market Analysis',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': 'The article discusses potential performance of Ethereum (ETH), Solana (SOL), and Rexas Finance (RXS) in the cryptocurrency market during summer 2025. It contains no mention of eClerx Services Ltd., its operations, financials, products, services, or any related business activities. As eClerx is a services company operating in a completely unrelated sector (likely business process outsourcing or IT services), there is no financial, operational, or strategic linkage to the cryptocurrency topics discussed. Therefore, the news has no direct or indirect impact on the company.'},
  {'company': 'Tata Consultancy Services (TCS)',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.65,
   'event_type': 'Internal Policy Change - Upskilling Programme Pause',
   'impact': 'Low',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': ['Pause in internal upskilling pathway affecting employee promotion prospects',
    'Uncertainty among employees regarding future career mobility and advancement'],
   'reasoning': "The article describes a pause in TCS's internal upskilling programme, which was a key route for employee promotions and skill development. While the policy change does not directly impact financial performance, revenue, earnings, or strategic initiatives, it affects employee morale and career progression pathways. However, the article does not specify any financial or operational consequences for the company, nor does it mention changes in revenue, market share, or business strategy. Industry observers note such pauses are often temporary and tied to workforce planning, which supports a neutral to low-impact assessment. The lack of explicit financial metrics or concrete business outcomes reduces confidence in a strong directional impact. Therefore, the sentiment is neutral with low to medium impact on the company's core operations and financials."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.0,
   'event_type': 'None',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses the financial and strategic developments of Life Insurance Corporation of India (LIC), not eClerx Services Ltd. There is no mention of eClerx in the content, and the events described—such as LIC's profit growth, digital transformation, premium income, market share, and regulatory changes—do not relate to eClerx's operations, products, or financial performance. Therefore, the news has no direct or indirect impact on eClerx Services Ltd. from an investment perspective."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.1,
   'event_type': 'Award Recognition',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': 'The article discusses an award received by Mr. S. Anish Pressena of the Pressana Group, which is unrelated to eClerx Services Ltd. There is no mention of eClerx Services in the content, nor any connection between Pressana Group and eClerx. Therefore, the news has no direct financial or operational impact on eClerx Services Ltd. The event is purely about a leadership award in the real estate sector and does not relate to earnings, revenue, product launches, partnerships, or any other financial metric relevant to eClerx. The clarity of the article is high, but the relevance to the company is zero. Confidence is low due to complete lack of connection between the company and the event.'},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.6,
   'event_type': 'Regulation',
   'impact': 'Low',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': 'The article discusses broad fiscal and tax policy changes in India under the Union Budget 2026, including modifications to TDS, TCS, income tax exemptions, and return filing timelines. However, none of these measures directly impact eClerx Services Ltd., which operates in the services sector primarily focused on business process outsourcing (BPO) and back-office services. The changes are general in nature and do not mention any specific effect on manpower services, supply chain, client compliance, or revenue streams tied to eClerx. While the inclusion of manpower services under TDS scope could theoretically affect service-based tax compliance, the proposed rate (1% or 2%) is not specific to eClerx or its clients. There is no explicit financial impact, revenue change, product launch, partnership, or operational detail related to the company. Therefore, the impact is minimal and indirect. The clarity of the article is high, but the absence of concrete, company-specific facts reduces confidence in a direct investment impact. The sentiment is neutral due to no clear positive or negative financial implication for the company.'},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.1,
   'event_type': 'Personal inheritance of Ratan Tata',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses Mohini Mohan Dutta's inheritance of Rs 588 crore from Ratan Tata, which is unrelated to eClerx Services Ltd. There is no mention of eClerx in the content, nor any financial, operational, strategic, or regulatory event affecting the company. The inheritance involves personal assets and legacy matters tied to Ratan Tata and his family, not eClerx. Therefore, from an investment perspective, this news has no direct or indirect impact on eClerx Services Ltd. The clarity of the article is moderate, but the event is entirely outside the scope of the company. No financial metrics, partnerships, earnings, or business developments related to eClerx are referenced."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.95,
   'event_type': 'Regulation',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses the launch of India's first private gold mine in Andhra Pradesh, operated by Geomysore Services India Pvt Ltd, which is unrelated to eClerx Services Ltd. There is no mention of eClerx in the content, nor any connection between the gold mining project and eClerx's services, operations, revenue, or business model. The event pertains to the mining sector and private investment in mineral exploration, not services, technology, or operations relevant to eClerx. Therefore, the news has no direct or indirect financial impact on eClerx Services Ltd. The clarity of the article is high, with concrete facts (investment amount, output projections, location, employment), but the event is entirely outside the company's domain. Confidence is high due to the clear absence of any link between the event and the company."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.3,
   'event_type': 'Market Trend - Investor Registrations',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses trends in retail investor registrations in India's stock markets, specifically noting a 2.5% month-on-month decline in new investor additions, with regional variations. However, it does not mention eClerx Services Ltd. directly, nor does it reference any financial performance, product launches, partnerships, regulatory changes, or other events relevant to the company. Since eClerx is a services company and the article focuses on investor behavior in stock markets without linking it to eClerx's operations, revenue, or business model, there is no direct or indirect financial impact on the company. The data is macroeconomic and sector-agnostic, thus the impact on eClerx is negligible. The clarity is moderate, but the absence of any concrete connection to the company reduces confidence in the relevance of the event."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.95,
   'event_type': 'Regulation',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses Bandhan Bank's strategic expansion in corporate lending and asset quality improvements, including NPA sales and secured lending focus. However, eClerx Services Ltd. is not mentioned or referenced in the article, and there is no direct or indirect link between the events described and eClerx's operations, revenue, earnings, or business model. As such, the news has no material financial impact on eClerx Services Ltd. The event is entirely unrelated to the company, making the impact zero. The clarity of the article is high, and all facts are concrete, but the absence of any connection to eClerx confirms no impact."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.0,
   'event_type': 'Interest Rate Announcement (Bank FD Rates for Senior Citizens)',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses FD interest rates offered by banks to senior citizens and does not mention any direct financial activity, product launch, partnership, earnings, regulatory change, or operational update related to eClerx Services Ltd. As eClerx is a services company and not directly involved in banking or fixed deposit offerings, the news has no material financial impact on the company or its operations. The content is purely informational and sector-agnostic, with no explicit connection to eClerx's business model, revenue, or performance. Therefore, the impact is neutral and zero."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.1,
   'event_type': 'Foreign Influence Campaign',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses OpenAI's findings on a foreign influence campaign involving Chinese operators using ChatGPT to generate content about U.S. data centre policies and trade tariffs. However, eClerx Services Ltd. is not mentioned or directly connected to any of the events described. The content pertains to AI policy, geopolitical interference, and U.S. energy debates, none of which have a direct financial or operational relevance to eClerx Services Ltd., which operates in the services industry without a clear link to AI data centres, policy debates, or international influence operations. Therefore, the news has no material impact on the company. The low confidence stems from the lack of any explicit connection between the event and eClerx's business operations, financials, or market position."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.3,
   'event_type': 'Macroeconomic and Sectoral Outlook',
   'impact': 'Low',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article discusses a macro-level investment outlook for India, highlighting growth themes such as manufacturing, services exports, consumption, and energy transition. While eClerx Services Ltd. operates in the services sector, the article does not mention any specific financial performance, product launch, partnership, regulatory change, or event directly impacting the company. There is no explicit reference to eClerx's revenue, earnings, market expansion, or operational developments. The sentiment is broadly positive for India's economy, but the lack of concrete, company-specific facts or financial metrics makes the impact on eClerx negligible. The confidence is low due to ambiguity and absence of direct relevance to the company's operations or financials."},
  {'company': 'eClerx Services Ltd.',
   'sentiment': 'Neutral',
   'sentiment_score': 0.0,
   'confidence': 0.3,
   'event_type': 'Government/Corporate Initiative (Non-Related)',
   'impact': 'No Impact',
   'time_horizon': 'Medium',
   'key_positive_factors': [],
   'key_negative_factors': [],
   'reasoning': "The article describes a national initiative launched by Gautam Adani, Vande Bharatam, aimed at promoting grassroots innovation and entrepreneurship across India. However, this initiative is not directly related to eClerx Services Ltd., which operates in the services sector primarily focused on business process outsourcing (BPO) and back-office services. There is no mention of eClerx in the article, no financial impact, no partnership, no product launch, no regulatory change, or any event that would affect eClerx's operations, revenue, or market position. The event is broadly sectoral and strategic at the national level but has no direct or indirect financial or operational linkage to eClerx. Therefore, the impact on the company is negligible, and the sentiment is neutral with low confidence due to lack of concrete financial or operational connection."}]}

In [26]:


df = news_df[["title", "content"]].copy()

dataset = Dataset.from_pandas(df, preserve_index=False)

def preprocess(batch):
    return {
        "messages": [
            [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": PROMPT.format(
                        company_name=company,
                        industry=industry,
                        title=title,
                        content=content,
                    ),
                },
            ]
            for title, content in zip(batch["title"], batch["content"])
        ]
    }

messages = dataset.map(preprocess, batched=True)
results = pipe(messages['messages'][:], batch_size=2)

Map: 100%|██████████| 17/17 [00:00<00:00, 6804.39 examples/s]

In [25]:
print(type(messages))
print(type(messages["messages"]))

<class 'datasets.arrow_dataset.Dataset'>
<class 'datasets.arrow_dataset.Column'>

In [16]:
results = pipe(
    messages["messages"],
    batch_size=2,
)

TypeError: can only concatenate str (not "Column") to str

In [10]:
non_neutral_sentiments = []
for row in tqdm(df.itertuples(index=False)):
    message = [
        {
            'role':'system',
            'content' : SYSTEM_PROMPT,
        },
        {
            'role':'user',
            'content': PROMPT.format(company_name = company,
                            industry = company, 
                            title = row.title, 
                            content = row.content),
        },
    ]

    result = pipe(message)

    sentiment = json.loads(result[0]['generated_text'][-1]['content'])

    if sentiment['sentiment'].lower()!='neutral':
        non_neutral_sentiments.append(sentiment)

NameError: name 'df' is not defined

0.675